# NOTE: The env groups should be first created in the Render dashboard
# Since they do not allow `sync: false` in env groups, this is seems to be the only way

projects:
  - name: gfed-bff-project
    environments:
      - name: production
        services:
          - type: web
            runtime: image
            plan: free
            name: gateway-prod
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/gateway:latest
            envVars:
              - fromGroup: bff-prod-env-group

          - type: web
            runtime: image
            plan: free
            name: content-prod
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/content:latest
            envVars:
              - fromGroup: bff-prod-env-group

          - type: web
            runtime: image
            plan: free
            name: products-prod
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/products:latest
            envVars:
              - fromGroup: bff-prod-env-group

          - type: web
            runtime: image
            plan: free
            name: orders-prod
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/orders:latest
            envVars:
              - fromGroup: bff-prod-env-group

          - type: web
            runtime: image
            plan: free
            name: customers-prod
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/customers:latest
            envVars:
              - fromGroup: bff-prod-env-group

      - name: smoke
        services:
          - type: web
            runtime: image
            plan: free
            name: gateway-smoke
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/gateway:latest
            envVars:
              - fromGroup: bff-smoke-env-group

          - type: web
            runtime: image
            plan: free
            name: content-smoke
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/content:latest
            envVars:
              - fromGroup: bff-smoke-env-group

          - type: web
            runtime: image
            plan: free
            name: products-smoke
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/products:latest
            envVars:
              - fromGroup: bff-smoke-env-group

          - type: web
            runtime: image
            plan: free
            name: orders-smoke
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/orders:latest
            envVars:
              - fromGroup: bff-smoke-env-group

          - type: web
            runtime: image
            plan: free
            name: customers-smoke
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/customers:latest
            envVars:
              - fromGroup: bff-smoke-env-group

      - name: qa
        services:
          - type: web
            runtime: image
            plan: free
            name: gateway-qa
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/gateway:latest
            envVars:
              - fromGroup: bff-qa-env-group

          - type: web
            runtime: image
            plan: free
            name: content-qa
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/content:latest
            envVars:
              - fromGroup: bff-qa-env-group

          - type: web
            runtime: image
            plan: free
            name: products-qa
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/products:latest
            envVars:
              - fromGroup: bff-qa-env-group

          - type: web
            runtime: image
            plan: free
            name: orders-qa
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/orders:latest
            envVars:
              - fromGroup: bff-qa-env-group

          - type: web
            runtime: image
            plan: free
            name: customers-qa
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/customers:latest
            envVars:
              - fromGroup: bff-qa-env-group
